version: '3.5'

services:
  springboot:
    image: anand2909/spring-boot-mongo
    container_name: webapp
    ports:
      - 8080:8080
    networks:
       webapp-net:
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo
    networks:
      webapp-net:
    restart: unless-stopped
    volumes:
      - mongobckp:/data/db
    
volumes:
  mongobckp:
    
networks:
  webapp-net:

