version: '3.5'

services:
  springboot:
    image: anand2909/spring-boot-mongo
    ports:
      - 8080:8080
    networks:
       - customoverlay1
    working_dir: /opt/app
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure 
      

  mongo:
    image: mongo
    container_name: springboot-mongo
    restart: always
    
volumes:
  vol1:
    
networks:
  customoverlay1:

