apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springapp-rc
  name: spring-controller
spec:
  replicas: 2
  selector:
    name: springapp
  template:
    metadata:
      name: springapp-pod
      labels:
        name: springapp
    spec:
      containers:
      - image: dockerp2pro/spring-boot-mongo:latest
        name: springapp-container
        ports:
        - name: springapp
          containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot-service
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: springapp
