apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springapp-rc
  name: spring-controller
spec:
  replicas: 2
  selector:
    name: springapp
  template:
    metadata:
      name: springapp-pod
      labels:
        name: springapp
    spec:
      containers:
      - image: anand2909/spring-boot-mongo:latest
        name: springapp-container
        ports:
        - name: springapp
          containerPort: 8080
---
# LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: springapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
