
# LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: springapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
